[phases.setup]
nixPkgs = ['nodejs']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx next build']

[start]
cmd = 'npm start'
env = { NODE_ENV = "production", PORT = "3000" }
